services:
  inference-gateway:
    image: synaxis/synaxis-inferencegateway:latest
    build:
      context: .
      dockerfile: src/InferenceGateway/WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - Synaxis__Providers__Groq__Key=your_key_here
      # - Synaxis__Providers__Cohere__Key=your_key_here
      # - Synaxis__Providers__Gemini__Key=your_key_here
      # - Synaxis__Providers__Cloudflare__Key=your_key_here
      # - Synaxis__Providers__OpenRouter__Key=your_key_here
